title: TCC Help
description: "Documentação para acompanhamento de TCCs do curso de Análise e Desenvolvimento de Sistemas"
baseurl: "/TCC-CADS" # altere isso para o nome do seu repositório no GitHub
url: "https://adsifs.github.io"
theme: jekyll-theme-cayman
theme_config:
  logo: "/assets/logo.svg"
  favicon: "/assets/favicon.ico"
