# Develop override settings

theme: minimal-mistakes-jekyll
remote_theme: null
url: http://localhost:4000
# baseurl: "/minimal-mistakes" # the subpath of your site, e.g. "/blog"
# repository: "adsifs/TCC-CADS"

analytics:
  provider: false

comments:
  disqus:
    shortname: "mmistakes-dev"

sass:
  style: expanded
