flowchart TD

%% Fases (definição de estilos)
    classDef fase1 fill:#E0F7FA,stroke:#00ACC1,color:#004D40,font-size:10px
    classDef fase2 fill:#F1F8E9,stroke:#7CB342,color:#33691E,font-size:10px
    classDef fase3 fill:#FFF3E0,stroke:#FB8C00,color:#E65100,font-size:10px
    classDef legenda fill:#f0f0f0,stroke:#cccccc,color:#333,font-size:12px

%% Grupos
 	subgraph Legenda
        L1["Fase 1: Escolha e <br>definição do tema"]
        L2["Fase 2: Estruturação <br>dos objetivos"]
        L3["Fase 3: Desenvolvimento <br> e finalização"]
    end
    subgraph Professor
        P1[Lista temas por <br>prioridade ou afinidade]
        P2[Avalia o objetivo geral]
        P3[Avalia os objetivos específicos]
        PValidaCrono[Valida cronograma]
        P4[Valida metodologia]
        P5[Correções finais<br> antes da apresentação]
        PC[Realiza correções<br> na escrita]
    end

    subgraph Aluno
        A1[Solicita apoio ao professor<br> com sugestão de temas]
        A2[Define tema com <br>apoio do orientador]
        A3[Define objetivo geral]
        A4[Elabora objetivos específicos <br> pelo menos 5]
        A5[Elabora cronograma <br>de entrega]
        A6[Elabora metodologia<br> de trabalho]
        A7[Elabora justificativa]
        A8[Realiza levantamento<br> bibliográfico]
        A9[Identifica trabalhos<br> semelhantes]
        A10[Referencial teórico]
        A11[Modela e documenta <br>o sistema]
        A12[Apresenta <br> TCC]
    end

%% Fluxo
    A1 --> P1 --> A2 --> A3 --> P2 --> A4 --> P3
    P3 --> A5
    A4 --> A5
    A5 --> PValidaCrono --> A6
    A6 --> P4
    A6 --> A7
    P4 --> A8 
    A8 --> A9 --> A10 --> A11
    P4 --> PC --> A8
    PC --> A9
    PC --> A10
    PC --> A11
    A11 --> P5 --> A12

%% Classes (Fases do trabalho)
    class A1,A2,A3,P1,P2 fase1
    class A4,A5,P3,PValidaCrono fase1
    class A6,A7,A8,A9,A10,A11,P4,PC fase2
    class P5,A12 fase3

%% Legenda compacta (com cores das fases)
   
    class L1 fase1
    class L2 fase2
    class L3 fase3
   
    style Legenda fill:#f0f0f0,stroke:#cccccc,stroke-width:1px,font-size:9px
    

    %% Ajustes para compactar as caixas de texto dentro da legenda
    style L1 font-size:9px
    style L2 font-size:9px
    style L3 font-size:9px
