name: "Geral"
description: Use este modelo para registrar sua sugestão.
body:
  - type: markdown
    attributes:
      value: |
        Descreva aqui a sua sugestão. Além do formato texto, use imagens e links para auxiliar na descrição.

        Agradecemos a sua contribuição!
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: |
        A riqueza de detalhes auxilia na análise do problema/sugestão ;) 
        Adicione:
        - Imagem
        - Vídeo
        - links
        ...
    validations:
      required: true
  - type: dropdown
    id: tipo
    attributes:
    label: Você acredita que isso seja um?
    options:
      - Erro/Bug
      - Link quebrado
      - Sugestão
      - Correção de texto
      - Outra coisa, não sei dizer.
    validations:
      required: true

  
